services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis_data/:/data
      - ./docker/redis/:/usr/local/etc/redis/:ro
    command: redis-server --save 60 1 --loglevel warning
    restart: on-failure:5
